.common: &common
    hostname: ~
    port: 22
    user: root
    password: ~
    longview-mysql-pass: ~
    forward_agent: true
    identity_file: ~
    stage: production
    app_path: ./vendor/intbizth/deployer-php/apps/tpl
    vhost_map_path: ./deploy/vhost_map.conf
    deploy_root: /var/www
    backend_name: default_backend
    backend_port: 8080
    backend_conf: ~
    local_parameters: ./app/config/parameters.yml
    repository: ~
    branch: master
    docker: ~
    cloudflare_proxy_used: false
    cloudflare:
        email: ~
        api_key: ~
        domain: ~
    defines: ~
    tasks:
        before: ~
        after: ~
        task: ~

.substitutions: &substitutions
    EDIT_ME_DEPLOY_ROOT: '{{deploy_root}}'
    EDIT_ME_DEPLOY_PATH: '{{deploy_path}}'
    EDIT_ME_PHP_FASTCGI: '{{php_fastcgi}}'
    EDIT_ME_SERVER_TIMEZONE: '{{timezone}}'

.environments: &environments
    php_version: 7.2
    php_fastcgi: /run/php/php7.2-fpm.sock
    cachetool: true
    cloudflare_proxy_used: false
    timezone: Asia/Bangkok
    writable_mode: chmod
    writable_chmod_mode: '0777'
    writable_use_sudo: false
    symfony_env: prod
    dump_assets: false
    sylius_theme_used: false
    shared_dirs:
        - var/log
        - var/sessions
        - public/media
    shared_files:
        - .env.prod
    writable_dirs:
        - var
    copy_dirs:
        - vendor
        - public/build
        - public/bundles
        - public/media
    copy_files: []
    copy_local_dirs:
        - public/build
    copy_local_files: ~
    # be careful filename when using in multi-backend mode.
    supervisors: ~
